// ATLVBA.idl: источник языка IDL для ATLVBA
//

// Этот файл будет обработан средством MIDL для
// создание библиотеки типов ($handlersafeidlname$.tlb) и кода маршалирования.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(566442d4-10d6-4437-b9d4-836bd6a64c04),
	version(1.0),
]
library ATLVBALib
{
	importlib("stdole2.tlb");
	typedef [public] void AnyType;
	const __int3264 NullPtr = 0;
	
	typedef enum CompareMethod {
		BinaryCompare = 0,
		TextCompare = 1
	} CompareMethod;

	//[
	//	uuid(DB8F8B36-848D-45D8-BF77-C6C1ADEABB1C), 
	//	dllname("ATLVBA.dll"),
	//	helpstring("Example functions module")
	//]
	//module MathFunctions{
		//[entry(1)]
		//double __stdcall ExampleFun(
		//	[in] double a,
		//	[in] double b);
	//};
	[
		uuid(9300AA31-2722-453F-9140-1082D95E486D),
		dllname("ATLVBA.dll"),
		hidden
	]
	module MemHelp{
		[entry("VarPtr")] __int3264 vp([in] void* Var);
		[entry("VarPtr")] __int3264 ap([in] SAFEARRAY(void)* Arr);
		[entry("VarPtr")] __int3264 ArrPtr([in] const SAFEARRAY(void)* Arr);
		[entry("GetMemPtr")] void GetMemPtr(const void* src, void* dst);
		[entry("GetMem1")] void GetMem1(const void* src, void* dst);
		[entry("GetMem2")] void GetMem2(const void* src, void* dst);
		[entry("GetMem4")] void GetMem4(const void* src, void* dst);
		[entry("GetMem8")] void GetMem8(const void* src, void* dst);
		[entry("GetMem16")] void GetMem16(const void* src, void* dst);
		[entry("GetMemVT")] void GetMemVT(const void* src, void* dst);		
		
		[entry("PutMemPtr")] void PutMemPtr(void* dst, __int3264 src);
		[entry("PutMem1")] void PutMem1(void* dst, byte src);
		[entry("PutMem2")] void PutMem2(void* dst, short src);
		[entry("PutMem4")] void PutMem4(void* dst, long src);
		[entry("PutMem8")] void PutMem8(void* dst, CY src);
		[entry("PutMem8")] void PutMemLL(void* dst, __int64 src);
		[entry("PutMemVT")] void PutMemVT(void* dst, VARIANT src);

		[entry("GetMem1"), propget]
		HRESULT __stdcall GetByt([in] void* Src, [out, retval] byte* bRetVal);
		[entry("PutMem1"), propput]
		HRESULT __stdcall PutByt([in] void* Dst, [in] byte bNewVal);

		[entry("GetMem2"), propget]
		HRESULT __stdcall GetInt([in] void* Src, [out, retval] short* iRetVal);
		[entry("PutMem2"), propput]
		HRESULT __stdcall PutInt([in] void* Dst, [in] short iNewVal);

		[entry("GetMem4"), propget]
		HRESULT __stdcall GetLng([in] void* Src, [out, retval] int* lRetVal);
		[entry("PutMem4"), propput]
		HRESULT __stdcall PutLng([in] void* Dst, [in] int lNewVal);

		[entry("GetMemPtr"), propget, helpstring("Returns or sets the value referenced by the source parameter cast to a DWord Long.")]
		HRESULT __stdcall GetPtr([in] void* Src, [out, retval] __int3264* pRetVal);
		[entry("PutMemPtr"), propput, ]
		HRESULT __stdcall PutPtr([in] void* Dst, [in] __int3264 pNewVal);
		
		//[entry("GetMemPtr"), propget]
		//HRESULT __stdcall StringPtr([in] BSTR* Src, [out, retval] __int3264* pRetVal);
		//[entry("VarPtr"), propget]
		//HRESULT __stdcall SPtr([in] BSTR Src, [out, retval] __int3264 pRetVal);
		[entry("PutMemPtr"), propput]
		HRESULT __stdcall PutStrPtr([in] BSTR* Src, [in] __int3264 pNewVal);
		
		[entry("GetMemPtr"), propget]
		HRESULT __stdcall SAPtr([in] SAFEARRAY(void)* Array, [out, retval] __int3264* pRetVal);
		[entry("PutMemPtr"), propput]
		HRESULT __stdcall SAPtr([in] SAFEARRAY(void)* Array, [in] __int3264 pNewVal);
		
		//[entry("GetMemPtr"), propget]
		//HRESULT __stdcall StrSAPtr([in] SAFEARRAY(BSTR)* Array, [out, retval] __int3264* lpRetVal);
		//[entry("PutMemPtr"), propput, ]
		//HRESULT __stdcall StrSAPtr([in] SAFEARRAY(BSTR)* Array, [in] __int3264 NewValue);

		[entry("GetMem8"), propget]
		HRESULT __stdcall GetCur([in] void* Src, [out, retval] CURRENCY* cRetVal);
		[entry("PutMem8"), propput]
		HRESULT __stdcall PutCur([in] void* Dst, [in] CURRENCY cNewVal);
		[entry("GetMem8"), propget]
		HRESULT __stdcall GetDbl([in] void* Src, [out, retval] double* dRetVal);
		[entry("PutMem8"), propput]
		HRESULT __stdcall PutDbl([in] void* Dst, [in] double dNewVal);
		
		[entry("MovePtr")] void MovePtr(void* dst, void* src);
		[entry("MovePtr"), helpstring("Перемещает только указатель SA, не заботясь о данных массива dst (предполагается, что он пустой)")] 
		void MoveAryPtr(SAFEARRAY(void)* dst, SAFEARRAY(void)* src);
		[entry("MoveAry"), helpstring("Безопасное перемещение массива, с освобождением массива назначения")] void MoveAry(SAFEARRAY(void)* dst, SAFEARRAY(void)* src);
		[entry("MoveStr"), helpstring("Безопасное перемещение строки, с освобождением строки назначения")] void MoveStr(BSTR* dst, BSTR* src);
		[entry("MoveVT"), helpstring("Безопасное перемещение варианта")] void MoveVT(void* dst, void* src);
		
		[entry("SwapPtr")] void SwapPtr(void* var1, void* var2);
		[entry("SwapPtr")] void SwapAry(SAFEARRAY(void)* var1, SAFEARRAY(void)* var2);
		[entry("SwapVT")] void SwapVT(VARIANT* var1, VARIANT* var2);

		[entry("memCmp")] long __stdcall memCmp(const void* Buf1, void* Buf2, __int3264 Size);
		[entry("memCpy")] __int3264 __stdcall memCpy(void* dst, void* src, __int3264 sz);
		[entry(3)] __int3264 memmem([in] void* pbTarget, [in] long cbTarget, [in] void* pbPattern, [in] long cbPattern);
		[entry("MemFindRev")] __int3264 MemFindRev([in] void* pWhere, [in] int szWhere, [in] void* pWhat, [in] int szWhat);
		[entry("MemFindRevW")] __int3264 MemFindRevW([in] void* pWhere, [in] int szWhere, [in] void* pWhat, [in] int szWhat);
	};
	module StrHelp{
		[entry("StrLen")] INT32 StrLen([in] BSTR str);
		[entry("StrLenB")] INT32 StrLenB([in] BSTR str);
		[entry("ArrLen")] INT32 ArrLen([in] SAFEARRAY(void)* Arr);
		[entry("ToAnsi")] BSTR ToAnsi([in] BSTR str);
		[entry("ToAnsi"), helpstring("Alias ToAnsi")] BSTR toA([in] BSTR str);
		[entry("FromAnsi")] BSTR FromAnsi([in] BSTR str);
		[entry("FromAnsi"), helpstring("Alias FromAnsi")] BSTR fmA([in] BSTR str);
		[entry("InStrB_")]
		INT32 InStrB_([in] int Start, [in] BSTR Where, [in] BSTR What);
		[entry("InStrB2")] 
		INT32 InStrB2([in] int Start, [in] BSTR Where, [in] BSTR What, [in] int Length);
		[entry("InStrB3")] 
		INT32 InStrB3([in] int Start, [in] BSTR Where, [in] BSTR What, [in] int lStop);
		[entry("InStrByt"), helpstring("Analogue of the InStrB function for byte arrays")]
		INT32 InStrByt([in] int Start, [in] SAFEARRAY(byte)* Where, [in] SAFEARRAY(byte)* What);
		[entry("InStrByt2")] 
		INT32 InStrByt2([in] int Start, [in] SAFEARRAY(byte)* Where, [in] SAFEARRAY(byte)* What, [in] int Length);
		[entry("InStrByt3")] 
		INT32 InStrByt3([in] int Start, [in] SAFEARRAY(byte)* Where, [in] SAFEARRAY(byte)* What, [in] int lStop);
		[entry("InStrRevB")] 
		long InStrRevB([in] BSTR psCheck, [in] BSTR psMatch, 
			[in, optional, defaultvalue(0)] long Start, 
			[in, optional, defaultvalue(BinaryCompare)] CompareMethod Compare);
		[entry("InStrRevB2")] 
		long InStrRevB2([in] BSTR psCheck, [in] BSTR psMatch,
			[in, optional, defaultvalue(0)] long Start, [in, optional, defaultvalue(0)] long Length, 
			[in, optional, defaultvalue(BinaryCompare)] CompareMethod Compare);
		[entry("InStrRevB3")]
		long InStrRevB3([in] BSTR psCheck, [in] BSTR psMatch,
			[in, optional, defaultvalue(0)] long Start, [in, optional, defaultvalue(0)] long EndFind,
			[in, optional, defaultvalue(BinaryCompare)] CompareMethod Compare);
		[entry("ToUTF8")] BSTR ToUTF8([in] const BSTR sInp);
		[entry("ToUTF8"), helpstring("Alias ToUTF8")] BSTR toU8([in] const BSTR sInp);
		[entry("FromUTF8")] BSTR FromUTF8([in] const BSTR sInp);
		[entry("FromUTF8"), helpstring("Alias FromUTF8")] BSTR fmU8([in] const BSTR sInp);
		[entry("UCaseA")] BSTR UCaseA([in] const BSTR psInp);
		[entry("LCaseA")] BSTR LCaseA([in] const BSTR psInp);
		[entry("StartsWith")] VARIANT_BOOL StartsWith(BSTR sWhere, BSTR sWhat);
		[entry("EndsWith")] VARIANT_BOOL EndsWith(BSTR sWhere, BSTR sWhat);
		[entry("StartsWithAry")] VARIANT_BOOL StartsWithByt(SAFEARRAY(byte)* Where, SAFEARRAY(byte)* What);
		[entry("EndsWithAry")] VARIANT_BOOL EndsWithByt(SAFEARRAY(byte)* Where, SAFEARRAY(byte)* What);
		[entry("StartsWithAry")] VARIANT_BOOL StartsWithInt(SAFEARRAY(short)* Where, SAFEARRAY(short)* What);
		[entry("EndsWithAry")] VARIANT_BOOL EndsWithInt(SAFEARRAY(short)* Where, SAFEARRAY(short)* What);
	};
	module ArrHelp{		
		[entry("isObjInit")] VARIANT_BOOL isArrayInit([in] SAFEARRAY(void)* Arr);		
		[entry("AssignVecV")]void AssignVecV(
			[in, out] SAFEARRAY(VARIANT)* arDst,
			[in] SAFEARRAY(VARIANT)* arSrc);
		[entry("AssignVecV"), propput, vararg]
		HRESULT __stdcall GroupAssigment(
			[in, out] SAFEARRAY(VARIANT)* ArgList, 
			[in, out] SAFEARRAY(VARIANT)* rhs);
		[entry("GetRefList"), propget, vararg]
		HRESULT __stdcall RefList(	
			[in, out] SAFEARRAY(VARIANT)* ArgList, 
			[out, retval] SAFEARRAY(VARIANT)* pOut);
		/*interface _Class1 : IDispatch {
			[id(0x68030001), propput, vararg]
			HRESULT PutRefList(
				[in, out] SAFEARRAY(VARIANT)* Dst,
				[in, out] SAFEARRAY(VARIANT)* rhs);
			[id(0x68030000), propget, vararg]
			HRESULT GetRefList(
				[in] long pAr,
				[in, out] SAFEARRAY(VARIANT)* ArgList,
				[out, retval] SAFEARRAY(VARIANT)*);
		};*/
		/*[entry("InitCallBack")] void InitCallBack(__int3264 pfn);
		[entry("TestProp"), propput, vararg]
		HRESULT __stdcall TestProp(
			[in, out] SAFEARRAY(VARIANT)* ArgList,
			[in, out] SAFEARRAY(VARIANT)* rhs);*/
	};
	module ZipHelp{
		[entry("UnzipFileToBytes")] SAFEARRAY(byte) UnzipFileToBytes(BSTR sFilePath, BSTR sZipPath);
	};
	[hidden]
	module CallHelp{
		[entry("Call0")] void __stdcall Call0([in] __int3264 fn, [in, out] void* ret, [in] int retSz);
		[entry("Call1")] void __stdcall Call1([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1);
		[entry("Call2")] void __stdcall Call2([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2);
		[entry("Call3")] void __stdcall Call3([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3);
		[entry("Call4")] void __stdcall Call4([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4);
		[entry("Call5")] void __stdcall Call5([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5);
		[entry("Call6")] void __stdcall Call6([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6);
		[entry("Call7")] void __stdcall Call7([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6, void* a7);
		[entry("Call8")] void __stdcall Call8([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6, void* a7, void* a8);
		[entry("Call9")] void __stdcall Call9([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6, void* a7, void* a8, void* a9);
		[entry("Call10")] void __stdcall Call10([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6, void* a7, void* a8, void* a9, void* a10);
		
		[entry("CCall0")] void __stdcall CCall0([in] __int3264 fn, [in, out] void* ret, [in] int retSz);
		[entry("CCall1")] void __stdcall CCall1([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1);
		[entry("CCall2")] void __stdcall CCall2([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2);
		[entry("CCall3")] void __stdcall CCall3([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3);
		[entry("CCall4")] void __stdcall CCall4([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4);
		[entry("CCall5")] void __stdcall CCall5([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5);
		[entry("CCall6")] void __stdcall CCall6([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6);
		[entry("CCall7")] void __stdcall CCall7([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6, void* a7);
		[entry("CCall8")] void __stdcall CCall8([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6, void* a7, void* a8);
		[entry("CCall9")] void __stdcall CCall9([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6, void* a7, void* a8, void* a9);
		[entry("CCall10")] void __stdcall CCall10([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2, void* a3, void* a4, void* a5, void* a6, void* a7, void* a8, void* a9, void* a10);
		[entry("Call2_"), helpstring("Экспериментальная версия")] 
			void __stdcall Call2_([in] __int3264 fn, [in, out] void* ret, [in] int retSz, void* a1, void* a2);
		//void __stdcall Call2([in] __int3264 fn, [in, out] void* ret, [in] int retSz, [in, optional, defaultvalue(NullPtr)] void* arg1, [in, optional, defaultvalue(NullPtr)] void* arg2);
	};

	[
		dllname("Kernel32.dll"),
		helpstring("Library Functions"),
		hidden
	]
	module kernel32{
		[entry("LoadLibraryW")]
		__int3264 __stdcall LoadLibW( [in] BSTR LibFileName );
		[entry("FreeLibrary")]
		long FreeLib( [in] __int3264 hLibModule );
		[entry("GetProcAddress")]
		__int3264 __stdcall GetProcAddr( [in] __int3264 hModule, [in] BSTR AnsiProcName );
		[entry("RtlMoveMemory")]
		void __stdcall CopyMem([in, out] void* dst, [in] const void* src, __int3264 sz);
	};
};